name: Generate snake animationMore actions

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: divyesh-singh-gehlot
          outputs: dist/snake.svg?palette=custom
          color_snake: "#FF00FF"
          color_dots: "#0a0a0a,#1f1f1f,#39FF14,#FF00FF,#00FFFF,#FF6EC7"

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
