name: Generate snake animation

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@platane/patch-custom-color
        with:
          github_user_name: divyesh-singh-gehlot
          outputs: dist/snake.svg
          palette: "custom"
          color_snake: "#00FFF7"
          color_dots: "#000000,#0f0f0f,#1a1a1a,#00FFF7,#00c2ff"

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
